export const ALL_MODULES = {
    PRODUCTS: "PRODUCTS",
    CATEGORIES: "CATEGORIES",
    PROMOTIONS: "PROMOTIONS",
    USERS: 'USERS',
    PERMISSIONS: 'PERMISSIONS',
    ROLES: 'ROLES',
    ORDERS: "ORDERS",
}